# Generated by Django 5.2.17 on 2026-09-23 06:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='risks_issue_project_fdac8e_idx'), models.Index(fields=['project', 'severity'], name='risks_issue_project_26839b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('COST', 'Cost'), ('SCHEDULE', 'Schedule'), ('QUALITY', 'Quality'), ('PROCUREMENT', 'Procurement'), ('CONTRACTOR', 'Contractor'), ('DESIGN', 'Design'), ('COMMERCIAL', 'Commercial'), ('REGULATORY', 'Regulatory'), ('SAFETY', 'Safety'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('probability', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('risk_score', models.PositiveSmallIntegerField(editable=False)),
                ('response', models.CharField(choices=[('AVOID', 'Avoid'), ('MITIGATE', 'Mitigate'), ('TRANSFER', 'Transfer'), ('ACCEPT', 'Accept')], default='MITIGATE', max_length=16)),
                ('mitigation', models.TextField(blank=True)),
                ('contingency', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MITIGATING', 'Mitigating'), ('MONITORING', 'Monitoring'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
            ],
            options={
                'ordering': ['-risk_score', '-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='risks_risk_project_f20864_idx'), models.Index(fields=['project', '-risk_score'], name='risks_risk_project_e59a36_idx')],
            },
        ),
    ]
