# Generated by Django 5.2.17 on 2026-10-02 17:42

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='documents.documentfolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('BOQ', 'Bill of quantities'), ('DRAWING', 'Drawing'), ('SCHEDULE', 'Schedule'), ('PAYMENT_DOCUMENT', 'Payment document'), ('REPORT', 'Report'), ('CORRESPONDENCE', 'Correspondence'), ('INSPECTION_EVIDENCE', 'Inspection evidence'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('file', models.FileField(upload_to=apps.documents.models._document_upload_path)),
                ('original_filename', models.CharField(max_length=200)),
                ('file_extension', models.CharField(max_length=10)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('document_group', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('change_notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder')),
            ],
            options={
                'ordering': ['-is_latest', '-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(fields=('project', 'parent', 'name'), name='documents_folder_project_parent_name_unique'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'document_type'], name='documents_d_project_4f1b21_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_group', 'is_latest'], name='documents_d_documen_acf67e_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('document_group', 'version'), name='documents_document_group_version_unique'),
        ),
    ]
