# Generated by Django 5.2.17 on 2026-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('project', 'name'), name='documents_folder_project_root_name_unique'),
        ),
    ]
