# Generated by Django 5.2.17 on 2026-10-02 17:42

import apps.inspections.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_type', models.CharField(choices=[('ROUTINE', 'Routine'), ('PAYMENT_VERIFICATION', 'Payment verification'), ('PROGRESS_VERIFICATION', 'Progress verification'), ('QUALITY', 'Quality'), ('MILESTONE', 'Milestone'), ('SPECIAL', 'Special')], default='ROUTINE', max_length=32)),
                ('inspection_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=16)),
                ('overall_status', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('OBSERVATION', 'Observation'), ('FAIL', 'Fail')], default='PENDING', editable=False, max_length=16)),
                ('recommendations', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='projects.project')),
            ],
            options={
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('PROGRESS', 'Progress'), ('QUALITY', 'Quality'), ('MATERIALS', 'Materials'), ('CONTRACTOR', 'Contractor'), ('SAFETY', 'Safety'), ('COMMERCIAL', 'Commercial'), ('DOCUMENTATION', 'Documentation'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('OBSERVATION', 'Observation'), ('NOT_APPLICABLE', 'Not applicable')], default='OBSERVATION', max_length=16)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=16)),
                ('recommendation', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.inspection')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('SCREENSHOT', 'Screenshot'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('file', models.FileField(upload_to=apps.inspections.models._evidence_upload_path)),
                ('original_filename', models.CharField(max_length=200)),
                ('file_extension', models.CharField(max_length=10)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='inspections.inspection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['project', 'status'], name='inspections_project_d5546e_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['project', 'inspection_type'], name='inspections_project_64b060_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionitem',
            index=models.Index(fields=['inspection', 'status'], name='inspections_inspect_487a07_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevidence',
            index=models.Index(fields=['project', 'evidence_type'], name='inspections_project_547825_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevidence',
            index=models.Index(fields=['inspection'], name='inspections_inspect_fb9301_idx'),
        ),
    ]
