# Generated by Django 5.2.17 on 2026-09-23 06:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("variation_number", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SCOPE_CHANGE", "Scope change"),
                            ("DESIGN_CHANGE", "Design change"),
                            ("SITE_CONDITION", "Site condition"),
                            ("CLIENT_REQUEST", "Client request"),
                            ("REGULATORY", "Regulatory"),
                            ("MATERIAL_SUBSTITUTION", "Material substitution"),
                            ("ERROR_OMISSION", "Error or omission"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=32,
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("UNDER_REVIEW", "Under review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("IMPLEMENTED", "Implemented"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PROPOSED",
                        max_length=16,
                    ),
                ),
                ("requested_date", models.DateField()),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_variations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_variations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="variations__project_f74b02_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "variation_number"),
                        name="variations_variation_project_number_unique",
                    )
                ],
            },
        ),
    ]
