# Generated by Django 5.2.17 on 2026-09-18 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PLATFORM_ADMIN", "Platform admin"),
                            ("ORGANIZATION_ADMIN", "Organization admin"),
                            ("PROJECT_MANAGER", "Project manager"),
                            ("PROJECT_CONTROLS", "Project controls"),
                            ("SITE_INSPECTOR", "Site inspector"),
                            ("CONSULTANT", "Consultant"),
                            ("CLIENT_OWNER", "Client owner"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="VIEWER",
                        max_length=32,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["organization__name", "user__email"],
                "indexes": [
                    models.Index(
                        fields=["organization", "role"],
                        name="organizatio_organiz_e1169f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "organization"),
                        name="organizations_membership_user_org_unique",
                    )
                ],
            },
        ),
    ]
